os: osx
osx_image: xcode8.2


env:
  - HOMEBREW_NO_AUTO_UPDATE=1


before_install:
  - brew install https://github.com/Homebrew/homebrew-core/raw/master/Formula/python3.rb
  - pip3 install --upgrade pip setuptools

install:
  - true

before_script:
  - make test/vint

script:
  - make test


notifications:
  email: false
